### ISSUE TITLE
solver performance

### ISSUE THREAD

**Issue by akoskm** [kai5z/BeamTrace2D#2]
I've just pushed a `perf.html` page which contains a wall layout which makes the algorithm to calculate the traces incredibly slow. There aren't that many walls and the resulting beamtrace doesn't have that many beams either. What could slow down the algorithm?

My first idea is that the hidden areas ie. the areas that are enclosed by walls and thus cannot be hit by any beam. Are they eliminated by the solver?

Any other ideas?

**Comment by kai5z** [comment]
Your guess as to the problem with the speed in your example is very likely true. There are no doubt ways to optimise this, maybe even presented in the publication I based the code on (you should have a look there). I would imagine that the beam tree explodes with complex reflections that do not happen.

I can’t at the moment prioritise this high enough for me to look into it any deeper, sorry about that. If you are able to optimize this I would very much like to hear your thoughts behind how you did it.

**Comment by akoskm** [comment]
> Your guess as to the problem with the speed in your example is very likely true. There are no doubt ways to optimise this, maybe even presented in the publication I based the code on (you should have a look there). I would imagine that the beam tree explodes with complex reflections that do not happen.

Yes, we come to a similar conclusion. Currently neither we have the time to improve the performances but at some point we might have to. This is not really a bug, only a limitation of the current implementation/publication you based the code on.

Since we are aware of this and there is a test which demonstrates the behaviour, I think I'm closing this issue.
