### ISSUE TITLE
module systems, npm package

### ISSUE THREAD

**Issue by akoskm** [kai5z/BeamTrace2D#3]
I've added compatibility for AMD and CommonJS module systems in https://github.com/kai5z/BeamTrace2D/commit/5283148671e427a91ada0562dccbdeb26a696444 but I'm wondering if we could also publish a npm package?

Thoughts?

**Comment by kai5z** [comment]
That's great! I see no reason not to, if you think it's a good idea?

**Comment by akoskm** [comment]
- npm - Yes, I think it is. I'm working on an app which uses browserify to package the client side code.
  So far I was able to pull everything from the npm registry except this.
- AMD/CommonJS - the old method of including the library with `<script>` tags will still work but we'll also support module loading systems like the CommonJS-like environment that NodeJS provides.

**Comment by akoskm** [comment]
Here's a brief summary of what I changed:
- npm package published: https://www.npmjs.com/package/beam-trace-2d
- `/vendor` dependencies removed, everything installs through `npm install`. I'm using the same major versions of libraries like did with `/vendor` 
- a simple http server has been added which serves as demo and can be started with `npm start`
- please check `packages.json` for _author_ and _license_ info
