### ISSUE TITLE
failed GET jquery.min.js when index.html opened from the file system

### ISSUE THREAD

**Issue by akoskm** [kai5z/BeamTrace2D#4]
```
index.html:9 GET file://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js net::ERR_FILE_NOT_FOUND
```

This is the error in Chrome when `index.html` is opened from the file system.
Since the project is not (yet) accompanied by any http server when someone creates a clone it might try to open `index.html` from the file system.
I suggest that we keep the reference to the jquery which is delivered with the project: `<script src="js/vendor/jquery-1.10.2.min.js"></script>`.

**Comment by kai5z** [comment]
Yeah, that sounds good.
